name: Generate GitHub Stats Card

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate GitHub Stats Card
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://github-readme-stats.vercel.app/api/top-langs/?username=Abrama1&count_private=true > top-langs.svg

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add top-langs.svg
          git commit -m "Update GitHub stats card"
          git push
